//! Generated MikroBUS mapping for UNI-DS v8.
//! Generated by MikroBUS Rust Tools. Re-apply the setup to regenerate this file.

#![allow(dead_code)]

use drv_name::*;

// mikroBUS 1
pub const MIKROBUS_1_AN: pin_name_t = GPIO_A3;
pub const MIKROBUS_1_RST: pin_name_t = GPIO_E11;
pub const MIKROBUS_1_CS: pin_name_t = GPIO_A4;
pub const MIKROBUS_1_SCK: pin_name_t = GPIO_A5;
pub const MIKROBUS_1_MISO: pin_name_t = GPIO_A6;
pub const MIKROBUS_1_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_1_PWM: pin_name_t = GPIO_D12;
pub const MIKROBUS_1_INT: pin_name_t = GPIO_D3;
pub const MIKROBUS_1_RX: pin_name_t = GPIO_B7;
pub const MIKROBUS_1_TX: pin_name_t = GPIO_B6;
pub const MIKROBUS_1_SCL: pin_name_t = GPIO_B8;
pub const MIKROBUS_1_SDA: pin_name_t = GPIO_B9;

// mikroBUS 2
pub const MIKROBUS_2_AN: pin_name_t = GPIO_C0;
pub const MIKROBUS_2_RST: pin_name_t = GPIO_E12;
pub const MIKROBUS_2_CS: pin_name_t = GPIO_B2;
pub const MIKROBUS_2_SCK: pin_name_t = GPIO_A5;
pub const MIKROBUS_2_MISO: pin_name_t = GPIO_A6;
pub const MIKROBUS_2_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_2_PWM: pin_name_t = GPIO_D13;
pub const MIKROBUS_2_INT: pin_name_t = GPIO_D4;
pub const MIKROBUS_2_RX: pin_name_t = GPIO_D6;
pub const MIKROBUS_2_TX: pin_name_t = GPIO_D5;
pub const MIKROBUS_2_SCL: pin_name_t = GPIO_B8;
pub const MIKROBUS_2_SDA: pin_name_t = GPIO_B9;

// mikroBUS 3
pub const MIKROBUS_3_AN: pin_name_t = GPIO_C2;
pub const MIKROBUS_3_RST: pin_name_t = GPIO_E13;
pub const MIKROBUS_3_CS: pin_name_t = GPIO_B4;
pub const MIKROBUS_3_SCK: pin_name_t = GPIO_A5;
pub const MIKROBUS_3_MISO: pin_name_t = GPIO_A6;
pub const MIKROBUS_3_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_3_PWM: pin_name_t = GPIO_D14;
pub const MIKROBUS_3_INT: pin_name_t = GPIO_D2;
pub const MIKROBUS_3_RX: pin_name_t = GPIO_D9;
pub const MIKROBUS_3_TX: pin_name_t = GPIO_D8;
pub const MIKROBUS_3_SCL: pin_name_t = GPIO_B8;
pub const MIKROBUS_3_SDA: pin_name_t = GPIO_B9;

// mikroBUS 4
pub const MIKROBUS_4_AN: pin_name_t = GPIO_C3;
pub const MIKROBUS_4_RST: pin_name_t = GPIO_E14;
pub const MIKROBUS_4_CS: pin_name_t = GPIO_C13;
pub const MIKROBUS_4_SCK: pin_name_t = GPIO_C10;
pub const MIKROBUS_4_MISO: pin_name_t = GPIO_C11;
pub const MIKROBUS_4_MOSI: pin_name_t = GPIO_C12;
pub const MIKROBUS_4_PWM: pin_name_t = GPIO_D15;
pub const MIKROBUS_4_INT: pin_name_t = GPIO_F3;
pub const MIKROBUS_4_RX: pin_name_t = GPIO_C7;
pub const MIKROBUS_4_TX: pin_name_t = GPIO_C6;
pub const MIKROBUS_4_SCL: pin_name_t = GPIO_F1;
pub const MIKROBUS_4_SDA: pin_name_t = GPIO_F0;

// mikroBUS 5
pub const MIKROBUS_5_AN: pin_name_t = GPIO_B1;
pub const MIKROBUS_5_RST: pin_name_t = GPIO_E15;
pub const MIKROBUS_5_CS: pin_name_t = GPIO_D7;
pub const MIKROBUS_5_SCK: pin_name_t = GPIO_C10;
pub const MIKROBUS_5_MISO: pin_name_t = GPIO_C11;
pub const MIKROBUS_5_MOSI: pin_name_t = GPIO_C12;
pub const MIKROBUS_5_PWM: pin_name_t = GPIO_B0;
pub const MIKROBUS_5_INT: pin_name_t = GPIO_E10;
pub const MIKROBUS_5_RX: pin_name_t = GPIO_C7;
pub const MIKROBUS_5_TX: pin_name_t = GPIO_C6;
pub const MIKROBUS_5_SCL: pin_name_t = GPIO_F1;
pub const MIKROBUS_5_SDA: pin_name_t = GPIO_F0;
