[package]
name = "drv_pwm"
version = "0.2.0"
edition = "2026"
author =  [
    "Leon Besnie leon.besnie@reseau.eseo.fr",
    "Ivan Ruzavin ivan.ruzavin98@gmail.com"
    ]

[profile.release]
opt-level = 'z'
lto = true

[profile.dev]
opt-level = 0
lto = false

[dependencies]
drv_name = {path = "../drv_name"}
hal_pwm = {path = "../../../hal/lib/pwm"}