cmake_path(CONVERT "${SEARCH_PATHS}" TO_CMAKE_PATH_LIST SEARCH_PATH_LIST NORMALIZE)
list(TRANSFORM SEARCH_PATH_LIST PREPEND "\"")
list(TRANSFORM SEARCH_PATH_LIST APPEND "\"")
list(TRANSFORM SEARCH_PATH_LIST PREPEND "-SP" )

list(JOIN SEARCH_PATH_LIST " " SEARCH_PATHS_ARG)

set(CMAKE_STATIC_LIBRARY_SUFFIX_MikroC ".a")
set(CMAKE_EXECUTABLE_SUFFIX_MikroC ".hex")
set(CMAKE_C_ARCHIVE_FINISH "")

set(CMAKE_C_ARCHIVE_CREATE "<CMAKE_MikroC_COMPILER> -ARH -NRL -b\"${CMAKE_BINARY_DIR}\" ${SEARCH_PATHS_ARG} -out <TARGET> <OBJECTS>")

set(CMAKE_INCLUDE_FLAG_MikroC "-IP")
set(CMAKE_INCLUDE_FLAG_SEP_MikroC " -IP")
set(CMAKE_MikroC_COMPILE_OBJECT)
string(APPEND CMAKE_MikroC_COMPILE_OBJECT
    "<CMAKE_MikroC_COMPILER> -p${MCU_NAME} -jcom -DL -NRL  -b\"${CMAKE_BINARY_DIR}\" -fo${OSC} <FLAGS> <DEFINES> ${SEARCH_PATHS_ARG} \"${JCFG_FILE}\"  <INCLUDES> -out <OBJECT> <SOURCE> \"${CORE_LIB}\""
)

set(CMAKE_MikroC_LINK_EXECUTABLE)
string(APPEND CMAKE_MikroC_LINK_EXECUTABLE
"<CMAKE_MikroC_COMPILER>  -p${MCU_NAME} -NRL -b\"${CMAKE_BINARY_DIR}\" -fo${OSC} <LINK_FLAGS> ${SEARCH_PATHS_ARG} \"${JCFG_FILE}\" -out <TARGET>  <OBJECTS> <LINK_LIBRARIES> \"${CORE_LIB}\""
)

set(CMAKE_MikroC_CREATE_STATIC_LIBRARY)
string(APPEND CMAKE_MikroC_CREATE_STATIC_LIBRARY
"<CMAKE_MikroC_COMPILER> -ARH -NRL -b\"${CMAKE_BINARY_DIR}\" ${SEARCH_PATHS_ARG} -out <TARGET> <OBJECTS> <LINK_LIBRARIES> \"${CORE_LIB}\""
)
