//! Generated MikroBUS mapping for Nucleo-F429ZI with Click Shield for Nucleo-144.
//! Generated by MikroBUS Rust Tools. Re-apply the setup to regenerate this file.

#![allow(dead_code)]

use drv_name::*;

// mikroBUS 1
pub const MIKROBUS_1_AN: pin_name_t = GPIO_C0;
pub const MIKROBUS_1_RST: pin_name_t = GPIO_A13;
pub const MIKROBUS_1_CS: pin_name_t = GPIO_A4;
pub const MIKROBUS_1_SCK: pin_name_t = GPIO_B3;
pub const MIKROBUS_1_MISO: pin_name_t = GPIO_B4;
pub const MIKROBUS_1_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_1_PWM: pin_name_t = GPIO_C6;
pub const MIKROBUS_1_INT: pin_name_t = GPIO_F13;
pub const MIKROBUS_1_RX: pin_name_t = GPIO_A10;
pub const MIKROBUS_1_TX: pin_name_t = GPIO_A9;
pub const MIKROBUS_1_SCL: pin_name_t = GPIO_H1;
pub const MIKROBUS_1_SDA: pin_name_t = GPIO_H0;

// mikroBUS 2
pub const MIKROBUS_2_AN: pin_name_t = GPIO_C1;
pub const MIKROBUS_2_RST: pin_name_t = GPIO_A14;
pub const MIKROBUS_2_CS: pin_name_t = GPIO_B12;
pub const MIKROBUS_2_SCK: pin_name_t = GPIO_B3;
pub const MIKROBUS_2_MISO: pin_name_t = GPIO_B4;
pub const MIKROBUS_2_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_2_PWM: pin_name_t = GPIO_C7;
pub const MIKROBUS_2_INT: pin_name_t = GPIO_D10;
pub const MIKROBUS_2_RX: pin_name_t = GPIO_D6;
pub const MIKROBUS_2_TX: pin_name_t = GPIO_D5;
pub const MIKROBUS_2_SCL: pin_name_t = GPIO_H1;
pub const MIKROBUS_2_SDA: pin_name_t = GPIO_H0;

// mikroBUS 3
pub const MIKROBUS_3_AN: pin_name_t = GPIO_A2;
pub const MIKROBUS_3_RST: pin_name_t = GPIO_F1;
pub const MIKROBUS_3_CS: pin_name_t = GPIO_G8;
pub const MIKROBUS_3_SCK: pin_name_t = GPIO_B3;
pub const MIKROBUS_3_MISO: pin_name_t = GPIO_B4;
pub const MIKROBUS_3_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_3_PWM: pin_name_t = GPIO_C8;
pub const MIKROBUS_3_INT: pin_name_t = GPIO_G4;
pub const MIKROBUS_3_RX: pin_name_t = GPIO_C11;
pub const MIKROBUS_3_TX: pin_name_t = GPIO_C10;
pub const MIKROBUS_3_SCL: pin_name_t = GPIO_H1;
pub const MIKROBUS_3_SDA: pin_name_t = GPIO_H0;

// mikroBUS 4
pub const MIKROBUS_4_AN: pin_name_t = GPIO_A3;
pub const MIKROBUS_4_RST: pin_name_t = GPIO_G10;
pub const MIKROBUS_4_CS: pin_name_t = GPIO_E11;
pub const MIKROBUS_4_SCK: pin_name_t = GPIO_B3;
pub const MIKROBUS_4_MISO: pin_name_t = GPIO_B4;
pub const MIKROBUS_4_MOSI: pin_name_t = GPIO_B5;
pub const MIKROBUS_4_PWM: pin_name_t = GPIO_C9;
pub const MIKROBUS_4_INT: pin_name_t = GPIO_G6;
pub const MIKROBUS_4_RX: pin_name_t = GPIO_D2;
pub const MIKROBUS_4_TX: pin_name_t = GPIO_C12;
pub const MIKROBUS_4_SCL: pin_name_t = GPIO_H1;
pub const MIKROBUS_4_SDA: pin_name_t = GPIO_H0;
